   # 4: '[WATCH] [TeamB] vs [TeamA] Live Online',
    # 5: '[LIVE] [TeamA] vs [TeamB] Live Free',
    # 6: '[ITV] [TeamB] vs [TeamA] Live Free',
    # 7: '[STREAMING] [TeamA] vs [TeamB] Live',
    # 8: '[FREE]>>> [TeamB] vs [TeamA] Live',
    # 9: '[HDQ] [TeamA] vs [TeamB] 2021 Live',
    # 10: '[GAME]>>> [TeamB] vs [TeamA] 2021 Live',